###
# @bot-written
# 
# WARNING AND NOTICE
# Any access, download, storage, and/or use of this source code is subject to the terms and conditions of the
# Full Software Licence as accepted by you before being granted access to this source code and other materials,
# the terms of which can be accessed on the Codebots website at https://codebots.com/full-software-licence. Any
# commercial use in contravention of the terms of the Full Software Licence may be pursued by Codebots through
# licence termination and further legal action, and be required to indemnify Codebots for any loss or damage,
# including interest and costs. You are deemed to have accepted the terms of the Full Software Licence on any
# access, download, storage, and/or use of this source code.
# 
# BOT WARNING
# This file is bot-written.
# Any changes out side of "protected regions" will be lost next time the bot makes any changes.
###

site_name: helloapp - helloapp User Docs
site_url: https://helloapp/docs
use_directory_urls: false
docs_dir: pages
pages:

# % protected region % [Customise your documentation nav as you see fit here] off begin

  - index.md
  - Site-Admin:
    - Users: 'admin/site-admin/users.md'
    - Groups: 'admin/site-admin/groups.md'
    - Site Settings: 'admin/site-admin/site-settings.md'
    - Emails: 'admin/site-admin/emails.md'
  - Entities:
    - Tank Entity: 'admin/entities/tank.md'
    - Fish Entity: 'admin/entities/fish.md'
    - Species Entity: 'admin/entities/species.md'
    - Role Entity: 'admin/entities/role.md'
    - Privilege Entity: 'admin/entities/privilege.md'
  - Behaviours:
    

    # % protected region % [Customise your documentation nav as you see fit here] end

    # % protected region % [Extend your nav with custom pages here] off begin
    # % protected region % [Extend your nav with custom pages here] end

theme:
    name: readthedocs
    custom_dir: 'harmony_theme/'
extra_css:
    - css/harmony_extra.css
markdown_extensions:
    - smarty
    - toc:
        permalink: "#"
        baselevel: 2
    - meta
    - tables
    - fenced_code
    - fontawesome_markdown
    - codehilite
extra:
    version: 0.0.0

# % protected region % [Add any extra configuration here] off begin
# % protected region % [Add any extra configuration here] end

